/*

 BACKGROUNDGRAPHICS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 364

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __backgroundGraphics_h_INCLUDE
#define __backgroundGraphics_h_INCLUDE

/* Bank of tiles. */
#define bgGraphicsBank 1

/* Super Gameboy palette 0 */
#define bgGraphicsSGBPal0c0 6076
#define bgGraphicsSGBPal0c1 8935
#define bgGraphicsSGBPal0c2 6596
#define bgGraphicsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bgGraphicsSGBPal1c0 6076
#define bgGraphicsSGBPal1c1 8935
#define bgGraphicsSGBPal1c2 6596
#define bgGraphicsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bgGraphicsSGBPal2c0 6076
#define bgGraphicsSGBPal2c1 8935
#define bgGraphicsSGBPal2c2 6596
#define bgGraphicsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bgGraphicsSGBPal3c0 6076
#define bgGraphicsSGBPal3c1 8935
#define bgGraphicsSGBPal3c2 6596
#define bgGraphicsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bgGraphicsCGBPal0c0 27424
#define bgGraphicsCGBPal0c1 29280
#define bgGraphicsCGBPal0c2 19808
#define bgGraphicsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bgGraphicsCGBPal1c0 25504
#define bgGraphicsCGBPal1c1 24352
#define bgGraphicsCGBPal1c2 27264
#define bgGraphicsCGBPal1c3 11298

/* Gameboy Color palette 2 */
#define bgGraphicsCGBPal2c0 26538
#define bgGraphicsCGBPal2c1 27520
#define bgGraphicsCGBPal2c2 32416
#define bgGraphicsCGBPal2c3 13412

/* Gameboy Color palette 3 */
#define bgGraphicsCGBPal3c0 28657
#define bgGraphicsCGBPal3c1 32649
#define bgGraphicsCGBPal3c2 32514
#define bgGraphicsCGBPal3c3 20611

/* Gameboy Color palette 4 */
#define bgGraphicsCGBPal4c0 28657
#define bgGraphicsCGBPal4c1 32767
#define bgGraphicsCGBPal4c2 32578
#define bgGraphicsCGBPal4c3 32448

/* Gameboy Color palette 5 */
#define bgGraphicsCGBPal5c0 32448
#define bgGraphicsCGBPal5c1 24526
#define bgGraphicsCGBPal5c2 17280
#define bgGraphicsCGBPal5c3 20768

/* Gameboy Color palette 6 */
#define bgGraphicsCGBPal6c0 28657
#define bgGraphicsCGBPal6c1 27607
#define bgGraphicsCGBPal6c2 32646
#define bgGraphicsCGBPal6c3 32448

/* Gameboy Color palette 7 */
#define bgGraphicsCGBPal7c0 6076
#define bgGraphicsCGBPal7c1 8935
#define bgGraphicsCGBPal7c2 6596
#define bgGraphicsCGBPal7c3 5344
/* Start of tile array. */
extern const void __bank_bgGraphicsBLK0;
extern const unsigned char bgGraphicsBLK0[];
/* Start of tile array. */
extern const void __bank_bgGraphicsBLK1;
extern const unsigned char bgGraphicsBLK1[];

#endif

/* End of BACKGROUNDGRAPHICS.H */
