/*

 SPRITEGRAPHICS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 35

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __spriteGraphics_h_INCLUDE
#define __spriteGraphics_h_INCLUDE

/* Bank of tiles. */
#define spriteGraphicsBank 1

/* Super Gameboy palette 0 */
#define spriteGraphicsSGBPal0c0 6076
#define spriteGraphicsSGBPal0c1 8935
#define spriteGraphicsSGBPal0c2 6596
#define spriteGraphicsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spriteGraphicsSGBPal1c0 6076
#define spriteGraphicsSGBPal1c1 8935
#define spriteGraphicsSGBPal1c2 6596
#define spriteGraphicsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spriteGraphicsSGBPal2c0 6076
#define spriteGraphicsSGBPal2c1 8935
#define spriteGraphicsSGBPal2c2 6596
#define spriteGraphicsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spriteGraphicsSGBPal3c0 6076
#define spriteGraphicsSGBPal3c1 8935
#define spriteGraphicsSGBPal3c2 6596
#define spriteGraphicsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spriteGraphicsCGBPal0c0 0
#define spriteGraphicsCGBPal0c1 31481
#define spriteGraphicsCGBPal0c2 31955
#define spriteGraphicsCGBPal0c3 17421

/* Gameboy Color palette 1 */
#define spriteGraphicsCGBPal1c0 0
#define spriteGraphicsCGBPal1c1 32767
#define spriteGraphicsCGBPal1c2 21140
#define spriteGraphicsCGBPal1c3 5285

/* Gameboy Color palette 2 */
#define spriteGraphicsCGBPal2c0 0
#define spriteGraphicsCGBPal2c1 16365
#define spriteGraphicsCGBPal2c2 10784
#define spriteGraphicsCGBPal2c3 6369

/* Gameboy Color palette 3 */
#define spriteGraphicsCGBPal3c0 6076
#define spriteGraphicsCGBPal3c1 8935
#define spriteGraphicsCGBPal3c2 6596
#define spriteGraphicsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spriteGraphicsCGBPal4c0 6076
#define spriteGraphicsCGBPal4c1 8935
#define spriteGraphicsCGBPal4c2 6596
#define spriteGraphicsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spriteGraphicsCGBPal5c0 6076
#define spriteGraphicsCGBPal5c1 8935
#define spriteGraphicsCGBPal5c2 6596
#define spriteGraphicsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spriteGraphicsCGBPal6c0 6076
#define spriteGraphicsCGBPal6c1 8935
#define spriteGraphicsCGBPal6c2 6596
#define spriteGraphicsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spriteGraphicsCGBPal7c0 6076
#define spriteGraphicsCGBPal7c1 8935
#define spriteGraphicsCGBPal7c2 6596
#define spriteGraphicsCGBPal7c3 5344
/* Start of tile array. */
extern const void __bank_spriteGraphics;
extern const unsigned char spriteGraphics[];

#endif

/* End of SPRITEGRAPHICS.H */
