/*

 TEXTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 20 x 18
   Tile set      : textGraphicsWithExtraTile.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __textMap_h_INCLUDE
#define __textMap_h_INCLUDE

#define textMapWidth 20
#define textMapHeight 18
#define textMapBank 1

#define textMap textMapPLN0
extern const void __bank_textMapPLN0;
extern const unsigned char textMapPLN0[];
extern const void __bank_textMapPLN01;
extern const unsigned char textMapPLN1[];

#endif

/* End of TEXTMAP.H */
