/*

 TRIANGLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 50
   Tile set      : scaledGraphics.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __triangleMap_h_INCLUDE
#define __triangleMap_h_INCLUDE

#define triangleMapWidth 32
#define triangleMapHeight 50
#define triangleMapBank 1

#define triangleMap triangleMapPLN0
extern const void __bank_triangleMapPLN0;
extern const unsigned char triangleMapPLN0[];
extern const void __bank_triangleMapPLN01;
extern const unsigned char triangleMapPLN1[];

#endif

/* End of TRIANGLEMAP.H */
